<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slideshow-wrapper-news</name>
   <tag></tag>
   <elementGuidId>c6ebc5ce-d109-4123-ac29-6b21af72e827</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;slideshow-wrapper-news&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;slideshow-wrapper-news&quot;]</value>
   </webElementProperties>
</WebElementEntity>
