<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab0_tr1_td5</name>
   <tag></tag>
   <elementGuidId>4320cbbc-c83d-4538-bfc8-c9cb1c1523cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;tab0&quot;]/div/table/tbody/tr[1]/td[5]</value>
   </webElementProperties>
</WebElementEntity>
