<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab0_tr2_td3</name>
   <tag></tag>
   <elementGuidId>e5746ff0-cb30-4268-b21f-46368f2348a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;tab0&quot;]/div/table/tbody/tr[2]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;tab0&quot;]/div/table/tbody/tr[2]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
