<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab0_tr1_td3</name>
   <tag></tag>
   <elementGuidId>4f51d672-c797-4092-ba3d-e3d3571c35a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;tab0&quot;]/div/table/tbody/tr[1]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;tab0&quot;]/div/table/tbody/tr[1]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
